steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Docker Image'
    args: ['build','-t','gcr.io/lumen-b-ctl-047/copilotui','.']
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Docker Push'
    args: ["push", "gcr.io/lumen-b-ctl-047/copilotui"]
  - name: 'gcr.io/cloud-builders/gke-deploy'
    id: 'Prepare deploy'
    args:
      - 'prepare'
      - '--image=gcr.io/lumen-b-ctl-047/copilotui'
      - '--app=copilotui'
      - '--namespace=default'
      - '--output=output'
  - name: 'gcr.io/cloud-builders/gke-deploy'
    id: 'Deploy current revision'
    args:
      - 'set-image'
      - '--filename=deployment.yaml'
      - '--namespace=default'
      - '--cluster=b-ctl-dev-cluster'
      - '--location=us-central1-c'
      - 'copilotui=gcr.io/lumen-b-ctl-047/copilotui:latest'

timeout: 2200s
images: ['gcr.io/lumen-b-ctl-047/copilotui']