steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build Docker Image'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/copilotui', '.']
- name: 'gcr.io/cloud-builders/docker'
  id: 'Docker Push'
  args: ["push", "gcr.io/$PROJECT_ID/copilotui"]
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'run'
    - 'deploy'
    - 'copilotui'
    - '--image=gcr.io/$PROJECT_ID/copilotui'
    - '--region=us-central1'
    - '--allow-unauthenticated'
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['bash', '-c', 'sed -i "s|image:.*|image: us-central1-docker.pkg.dev/lumen-b-ctl-047/b-ctl-047-artifact/copilotui|g" deployment.yaml']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['bash', '-c', 'sed -i "s|port:.*|port: 3000|g" service.yaml']
- name: 'gcr.io/cloud-builders/gke-deploy'
  args: ['apply', '--filename=deployment.yaml', '--namespace=default', '--cluster=b-ctl-dev-cluster', '--location=us-central1-c']
- name: 'gcr.io/cloud-builders/gke-deploy'
  args: ['apply', '--filename=service.yaml', '--namespace=default', '--cluster=b-ctl-dev-cluster', '--location=us-central1-c']

