apiVersion: apps/v1
kind: Deployment
metadata:
  name: copilotui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: copilotui
  template:
    metadata:
      labels:
        app: copilotui
    spec:
      containers:
      - name: copilotui
        image: gcr.io/lumen-b-ctl-047/copilotui:latest
        ports:
        - containerPort: 3000